AllCops:
  TargetRubyVersion: 3.2.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'ag_downloader.gemspec'

Metrics/MethodLength:
  Exclude:
    - 'lib/ag_downloader.rb'